spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MicroServiceAccounts
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update  # Options: create, create-drop, update, validate, none
    show-sql: true      # Set to false in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Set to false in production
  
# Optional: Logging configuration for database queries
logging:
  level:
    org.hibernate.SQL: DEBUG           # Set to INFO or WARN in production
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Set to INFO in production